name: Regression suite

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
    uses: actions/checkout@v2

    -name: Set up python
    uses: actions/setup-python@v2
    
    with:
      python-version: '3.13'

    - name: Install dependencies
      run:
      
    

    
    
